version: '3'

services:
  mongo:
    image: 'mongo:3.4.1'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  api:
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:8080'
    environment:
      - TWITTER_CONSUMER_KEY=<your key>
      - TWITTER_CONSUMER_SECRET=<your key>
      - TWITTER_ACCESS_TOKEN_KEY=<your key>
      - TWITTER_ACCESS_TOKEN_SECRET=<your key>
      - MONGO_URL=mongodb://mongo:27017/api-mongo
volumes:
  mongo: